services:
  registry:
    image: registry:2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.registry.rule=Host(`registry.msolsys.pl`) || Host(`registry.msolsys.com`)"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.tls.certresolver=myresolver"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=200000000000"
      
      - "traefik.http.middlewares.registryHeaders.headers.customresponseheaders.Strict-Transport-Security=max-age=63072000; includeSubDomains; preload"
      - "traefik.http.middlewares.registryHeaders.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.routers.registry.middlewares=registryHeaders"
    volumes:
      - /registrypwd/:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - traefik

networks:
  traefik:
    external: true